dist: xenial
language: python

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

install:
  - pip install poetry
  - curl -fsS -o /tmp/get-poetry.py https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python /tmp/get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install -v
  - poetry build -v

script:
  - make test

matrix:
  allow_failures:
  - python: "nightly"

notifications:
  on_success: change
  on_failure: always
